name: shared_code
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  equatable: ^0.6.1
  uuid: ^2.0.2
  rxdart: ^0.22.3
  intl: ^0.16.0
  dio: ^3.0.3
  kiwi: ^0.2.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
  mockito: ^4.1.1
  build_runner: ^1.7.2
  kiwi_generator: ^0.4.0
